title: tree

author: arashrun

links:
  github: https://github.com/arashrun
  
favicon: /favicon.ico

# valine 
valine:
    # 评论
    enableComment: false 
    # 阅读量
    enableCounter: true
    # valine appID
    appID:
    # valine appKey
    appKey:
    placeholder: 请输入评论
    avatar: retro

gitalk:
    enable: true
    clientID: d91e94a64a0bd6162192
    clientSecrets: dea5446950bd4dbd03f7c459e78838a581b4658c
    github_repo: https://github.com/arashrun/hexo_comments
    repo_owner: arashrun
    distractionFreeMoe: true

# 是否开启“不蒜子”统计访问量
busuanzi: true

# 底部版权开始年份
siteStartYear: 2019

####### 站外搜索配置 #####
# 站点如果【被搜索引擎收录】，可以配置通过搜索引擎全站搜索
# searchEngine：搜索引擎，不配置则默认为谷歌，可替换为百度等其他搜索引擎的搜索 URL
#   https://www.baidu.com/s?wd=
#   https://www.google.com/search?q=
# homeHost：要搜索的站点域名，不配置默认取当前页面的域名
searchEngine: https://www.google.com/search?q=
homeHost: arashrun.github.io

tags: true
categories: true

# 左侧导航栏，用文件名还是文章名
sidebar:
  # usePostTitle 为 ture 用文章名，不填或为 false 用文件名
  usePostTitle: false
